language: java
sudo: false
install: true

jdk:
  - oraclejdk8

env:
  - DATABASE=H2
  - DATABASE=POSTGRES
  - DATABASE=MYSQL

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_4444.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :4444 -ac -screen 0 1280x1024x16"

script:
  - ./travis.sh

cache:
  directories:
    - '$HOME/.m2/repository'

before_cache:
  - 'rm -rf $HOME/.m2/repository/org/codehaus/sonar'

notifications:
  email: false

addons:
  sauce_connect: true
